package com.MyBatisDemo.mapperGenerator;

import com.MyBatisDemo.entityGenerator.User;
import com.MyBatisDemo.entityGenerator.UserCondition;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Feb 24 22:06:26 CST 2020
     */
    long countByExample(UserCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Feb 24 22:06:26 CST 2020
     */
    int deleteByExample(UserCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Feb 24 22:06:26 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Feb 24 22:06:26 CST 2020
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Feb 24 22:06:26 CST 2020
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Feb 24 22:06:26 CST 2020
     */
    List<User> selectByExample(UserCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Feb 24 22:06:26 CST 2020
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Feb 24 22:06:26 CST 2020
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Feb 24 22:06:26 CST 2020
     */
    int updateByExample(@Param("record") User record, @Param("example") UserCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Feb 24 22:06:26 CST 2020
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Feb 24 22:06:26 CST 2020
     */
    int updateByPrimaryKey(User record);
}